[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "gevent>=25.9.1",
    "gunicorn>=23.0.0",
    "starlette>=0.48.0",
    "uvicorn>=0.37.0",
]
